// Phase 6.1 — the transparency-rule classifier (pure; no DB, no AI, no React).
// Given a raw message and the current viewer, decide how it renders. The one hard
// rule (ORIGINAL-SPEC §8, mirrored in the chat snapshot test): an AI `assistant`
// message is ALWAYS labeled and visually distinct from the human `coach`, and the
// coach avatar appears for coach messages and nothing else. Keeping this in one
// tested function means the merge gate can't silently blur the line.

export type MessageSender = "client" | "coach" | "system" | "assistant";

export type MessageKind =
  | "text"
  | "voice"
  | "photo"
  | "card"
  | "plan_delivery"
  | "log_confirmation"
  | "reminder"
  | "interview";

export interface RawMessage {
  id: string;
  sender: MessageSender;
  kind: MessageKind;
  body: string | null;
  payload?: unknown;
  createdAt: string;
  replyTo?: string | null;
  readAt?: string | null;
  clientTag?: string | null;
}

/** The two perspectives a thread is viewed from. */
export type Viewer = "client" | "coach";

/** Whose side of the thread a bubble sits on, from the viewer's perspective. */
export type Align = "mine" | "theirs";

/**
 * The visual identity a message is rendered with. Exhaustive and never collapsed
 * into one another — `assistant` (AI) and `coach` (human) are distinct voices.
 */
export type Voice = MessageSender;

/** Kinds that render as an inline structured card rather than a chat bubble. */
const STRUCTURED_KINDS: ReadonlySet<MessageKind> = new Set<MessageKind>([
  "card",
  "plan_delivery",
  "log_confirmation",
]);

export interface MessageView {
  id: string;
  voice: Voice;
  align: Align;
  /** Generated by the AI assistant (the model wrote it). */
  isAi: boolean;
  /** Not a live human — the AI assistant OR an automated system message. */
  automated: boolean;
  /** The badge shown next to non-human messages; null for client/coach. */
  label: string | null;
  /** The trainer avatar — coach messages only, never AI/system/client. */
  showCoachAvatar: boolean;
  kind: MessageKind;
  body: string;
  /** Render as an inline card (check-in, meal confirm, plan delivery) not a bubble. */
  isStructured: boolean;
  createdAt: string;
  replyTo: string | null;
  /** Whether the recipient has read this message (drives the read tick). */
  readAt: string | null;
  /** The offline-dedupe tag, so an optimistic send can reconcile its realtime echo. */
  clientTag: string | null;
  /** Structured payload (check-in card options, plan-delivery refs, …). */
  payload: Record<string, unknown> | null;
}

export function toMessageView(msg: RawMessage, viewer: Viewer): MessageView {
  const isAi = msg.sender === "assistant";
  const isSystem = msg.sender === "system";
  const isCoach = msg.sender === "coach";

  const label = isAi ? "AI assistant" : isSystem ? "Automated" : null;

  return {
    id: msg.id,
    voice: msg.sender,
    // A message is "mine" only when the viewer authored it.
    align: msg.sender === viewer ? "mine" : "theirs",
    isAi,
    automated: isAi || isSystem,
    label,
    showCoachAvatar: isCoach,
    kind: msg.kind,
    body: msg.body ?? "",
    isStructured: STRUCTURED_KINDS.has(msg.kind),
    createdAt: msg.createdAt,
    replyTo: msg.replyTo ?? null,
    readAt: msg.readAt ?? null,
    clientTag: msg.clientTag ?? null,
    payload: (msg.payload as Record<string, unknown> | undefined) ?? null,
  };
}

/** Map a raw Supabase Realtime `payload.new` row (snake_case) into a RawMessage. */
export function rawFromRow(row: Record<string, unknown>): RawMessage {
  return {
    id: String(row.id),
    sender: row.sender as RawMessage["sender"],
    kind: row.kind as RawMessage["kind"],
    body: (row.body as string | null) ?? null,
    payload: row.payload,
    createdAt: String(row.created_at),
    replyTo: (row.reply_to as string | null) ?? null,
    readAt: (row.read_at as string | null) ?? null,
    clientTag: (row.client_tag as string | null) ?? null,
  };
}
